module.exports = {
    contentBBVA:[
        {text:"Constacia de Estudio", style:"header", alignment: 'center',  bold: true},
        {text:"Los algoritmos se han creado, modificado y utilizado a lo largo de la historia, hace más de 500 años cuando los sumerios ilustraron tablas de arcilla una estructura de repetición utilizado ara distribuir de forma equitativa la cosecha de granos entre un número variables de hombres. Como hemos visto el uso de los algoritmos se han utilizado tanto en la ciencia como en la producción. En la n geniería de procesos se utiliza para él estudio de tiempos y movimientos y tomar la mejor decisión en la implementación de procedimientos productivos; en la ciencia y la tecnología se utiliza para procesar los datos y hacer los cálculos más rápidos y procesar grandes cantidades de volúmenes de datos; en la actualidad los algoritmos se están utilizando en  todas las áreas de las ciencias y las tecnologías del ser humano, con la tecnología de las soluciones del internet de las cosas, Big Data, la industria 4.0, y la nueva computación cuántica Todo el mundo de este país debería saber programar”, esta frase de Steve Jobs me dejó en claro que  aprender a programar ayudaría a todos y en particular a los alumnos del nivel bachillerato a resolver todo tipo de problemas y procesar un gran volumen de información por la lógica cuando se desarrolla un algoritmo,  además deja en claro los procesos secuenciales y plasmados y de forma que cuando se tenga la solución se pueda analizar el algoritmo y se pueda mejorar los procesos, dando mantenimiento a estas soluciones o implementaciones a soluciones mayores", style: "normal", alignment: 'justify'}
    ],
    contentBasico:[
        {text:"Constacia de Estudio del Alumno DE TIPO BASICO", style:"header"},
        {text:"Los algoritmos se han creado, modificado y utilizado a lo largo de la historia, hace más de 500 años cuando los sumerios ilustraron tablas de arcilla una estructura de repetición utilizado ara distribuir de forma equitativa la cosecha de granos entre un número variables de hombres. Como hemos visto el uso de los algoritmos se han utilizado tanto en la ciencia como en la producción. En la n geniería de procesos se utiliza para él estudio de tiempos y movimientos y tomar la mejor decisión en la implementación de procedimientos productivos; en la ciencia y la tecnología se utiliza para procesar los datos y hacer los cálculos más rápidos y procesar grandes cantidades de volúmenes de datos; en la actualidad los algoritmos se están utilizando en  todas las áreas de las ciencias y las tecnologías del ser humano, con la tecnología de las soluciones del internet de las cosas, Big Data, la industria 4.0, y la nueva computación cuántica Todo el mundo de este país debería saber programar”, esta frase de Steve Jobs me dejó en claro que  aprender a programar ayudaría a todos y en particular a los alumnos del nivel bachillerato a resolver todo tipo de problemas y procesar un gran volumen de información por la lógica cuando se desarrolla un algoritmo,  además deja en claro los procesos secuenciales y plasmados y de forma que cuando se tenga la solución se pueda analizar el algoritmo y se pueda mejorar los procesos, dando mantenimiento a estas soluciones o implementaciones a soluciones mayores", style: "normal"}
    ]
}